export { default as Navbar } from "./navbar/Navbar";
export { default as Cart } from "./navbar/Cart";
export { default as Notification } from "./navbar/Notification";
export { default as UserProfile } from "./navbar/UserProfile";
export { default as Chat } from "./navbar/Chat";
export { default as Sidebar } from "./Sidebar";
export { default as ThemeSettings } from "./ThemeSettings";
export { default as BarChartComponent } from './dashboard/BarChart'
export { default as PieChartComponent } from "./dashboard/PieChart";
export { default as SalesTable } from './sales/SalesTable'
export { default as NewCustomer } from './customers/NewCustomer'
export { default as IndividualSalesLog } from './sales/IndividualSalesLog'
export { default as CustomerInfo } from './customers/CustomerInfo'
export { default as IndividualReturn } from './office/IndividualReturn';
export { default as SingleProduct } from './inventoryLog/SingleProduct';
export { default as NewCategory } from './stocks/NewCategory';
export { default as EditStockModal } from './stocks/EditStockModal';